#!/bin/sh
set -eu

cat > /usr/share/nginx/html/env.js <<EOF
window.__HAPPABI_ENV__ = {
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-}",
  VITE_BACKEND_URL: "${VITE_BACKEND_URL:-}",
  VITE_SOCKET_URL: "${VITE_SOCKET_URL:-}",
  VITE_AWS_REGION: "${VITE_AWS_REGION:-}",
  VITE_AWS_COGNITO_USER_POOL_ID: "${VITE_AWS_COGNITO_USER_POOL_ID:-}",
  VITE_AWS_COGNITO_CLIENT_ID: "${VITE_AWS_COGNITO_CLIENT_ID:-}",
  VITE_AWS_COGNITO_DOMAIN: "${VITE_AWS_COGNITO_DOMAIN:-}",
  VITE_COGNITO_REDIRECT_SIGN_IN: "${VITE_COGNITO_REDIRECT_SIGN_IN:-}",
  VITE_COGNITO_REDIRECT_SIGN_OUT: "${VITE_COGNITO_REDIRECT_SIGN_OUT:-}"
};
EOF

exec nginx -g 'daemon off;'